export const dummyClinics: any[] = [
	{
		name: 'Aster Clinic',
		location: 'Al Reem, Abu Dhabi',
		kilometers: 3,
		isFavorite: false,
		isSponsored: false,
		image: require('../../../assets/app/Home/danat.png'),
		isNearby: true,
	},
	{
		name: 'Cleaveland Clinic',
		location: 'Al Reem, Abu Dhabi',
		kilometers: 3,
		isFavorite: true,
		isSponsored: false,
		image: require('../../../assets/app/Home/sheik.png'),
		isNearby: true,
	},
	{
		name: 'Kaya Skin Clinic',
		location: 'Al Reem, Abu Dhabi',
		kilometers: 3,
		isFavorite: false,
		isSponsored: true,
		image: require('../../../assets/app/NearbyClinics/health.png'),
		isNearby: true,
	},
	{
		name: 'Harley Street Medical Clinic',
		location: 'Al Reem, Abu Dhabi',
		kilometers: 3,
		isFavorite: false,
		isSponsored: false,
		image: require('../../../assets/app/Home/danat.png'),
		isNearby: false,
	},
	{
		name: 'Cleaveland Clinic',
		location: 'Al Reem, Abu Dhabi',
		kilometers: 3,
		isFavorite: true,
		isSponsored: false,
		image: require('../../../assets/app/Home/sheik.png'),
		isNearby: false,
	},
	{
		name: 'Kaya Skin Clinic',
		location: 'Al Reem, Abu Dhabi',
		kilometers: 3,
		isFavorite: false,
		isSponsored: true,
		image: require('../../../assets/app/NearbyClinics/health.png'),
		isNearby: false,
	},
	{
		name: 'Harley Street Medical Clinic',
		location: 'Al Reem, Abu Dhabi',
		kilometers: 3,
		isFavorite: false,
		isSponsored: false,
		image: require('../../../assets/app/Home/danat.png'),
		isNearby: false,
	},
]
